/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.WarehouseRole;

import Business.Enterprise.Enterprise;
import Business.Organization.BillingOrganization;

import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BillingWorkRequest;
import Business.WorkQueue.WarehouseWorkRequest;
import Business.WorkQueue.WorkRequestDistribution;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author arpit
 */
public class WarehouseRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WarehouseRequestJPanel
     */
    
    JPanel userProcessContainer;
    WarehouseWorkRequest warehouseWorkRequest;
    Enterprise enterprise;
    UserAccount account;
    public WarehouseRequestJPanel(JPanel userProcessContainer, WarehouseWorkRequest request, UserAccount account, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.warehouseWorkRequest = request;
        this.enterprise=enterprise;
        populaterequest(request);
        this.account=account;
    }
    
    public void populaterequest(WarehouseWorkRequest request){
        prodNameDispTxt.setText(request.getProductName());
        quantityDisplayTxt.setText(request.getQuantity()+"");
        addNoteDisplayTxt.setText(request.getAddNote());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prodNameDispTxt = new javax.swing.JTextField();
        quantityDisplayTxt = new javax.swing.JTextField();
        dateDisplayTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addNoteDisplayTxt = new javax.swing.JLabel();
        acceptJButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        backJButton = new javax.swing.JButton();
        rejectJButton = new javax.swing.JButton();

        prodNameDispTxt.setEditable(false);
        prodNameDispTxt.setMinimumSize(new java.awt.Dimension(56, 22));
        prodNameDispTxt.setPreferredSize(new java.awt.Dimension(100, 22));
        prodNameDispTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodNameDispTxtActionPerformed(evt);
            }
        });

        quantityDisplayTxt.setEditable(false);
        quantityDisplayTxt.setMinimumSize(new java.awt.Dimension(56, 22));
        quantityDisplayTxt.setPreferredSize(new java.awt.Dimension(100, 22));

        dateDisplayTxt.setEditable(false);
        dateDisplayTxt.setMinimumSize(new java.awt.Dimension(56, 22));
        dateDisplayTxt.setPreferredSize(new java.awt.Dimension(100, 22));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Order Details");

        jLabel3.setText("Product Name");

        jLabel4.setText("Quantity");

        addNoteDisplayTxt.setText("Distributor's Note");

        acceptJButton.setBackground(new java.awt.Color(71, 0, 0));
        acceptJButton.setForeground(new java.awt.Color(255, 255, 255));
        acceptJButton.setText("Accept");
        acceptJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptJButtonActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(71, 0, 0));
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("BACK");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        rejectJButton.setBackground(new java.awt.Color(71, 0, 0));
        rejectJButton.setForeground(new java.awt.Color(255, 255, 255));
        rejectJButton.setText("Reject");
        rejectJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(backJButton)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(addNoteDisplayTxt))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(quantityDisplayTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(dateDisplayTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(prodNameDispTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(acceptJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(rejectJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodNameDispTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityDisplayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateDisplayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNoteDisplayTxt))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptJButton)
                    .addComponent(rejectJButton))
                .addContainerGap(342, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void prodNameDispTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodNameDispTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodNameDispTxtActionPerformed

    private void acceptJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptJButtonActionPerformed
     
        warehouseWorkRequest.setOrderStatus(1);
        warehouseWorkRequest.setOrderflag(1);
        
        WorkRequestDistribution bwr= warehouseWorkRequest;
        bwr.setProductName(warehouseWorkRequest.getProductName());
        bwr.setQuantity(warehouseWorkRequest.getQuantity());
        bwr.setAddNote(warehouseWorkRequest.getAddNote());
        bwr.setOrderStatus(warehouseWorkRequest.isOrderStatus());
        //bwr.setOrderflag(warehouseWorkRequest.getOrderflag());
       // bwr.setManagerNote(managerNote.getText());
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof BillingOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getworkRequestOrderList().add(warehouseWorkRequest);
            account.getWorkQueue().getworkRequestOrderList().add(warehouseWorkRequest);
        }
        
    }//GEN-LAST:event_acceptJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
    
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        WarehouseWorkAreaJPanel dwjp = (WarehouseWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void rejectJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectJButtonActionPerformed
        // TODO add your handling code here:
        warehouseWorkRequest.setOrderStatus(-1);
        warehouseWorkRequest.setOrderflag(1);   
    }//GEN-LAST:event_rejectJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptJButton;
    private javax.swing.JLabel addNoteDisplayTxt;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField dateDisplayTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField prodNameDispTxt;
    private javax.swing.JTextField quantityDisplayTxt;
    private javax.swing.JButton rejectJButton;
    // End of variables declaration//GEN-END:variables
}
