/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.TransportRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BillingWorkRequest;
import Business.WorkQueue.WarehouseWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class TransportProcessJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TransportProcessJPanel
     */
    JPanel userProcessContainer;
    WarehouseWorkRequest warehouseRequest;
    static boolean generateClicked=false;
    Enterprise enterprise;
    UserAccount account;
    
    public TransportProcessJPanel(JPanel userProcessContainer, WarehouseWorkRequest warehouseRequest, Enterprise enterprise, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.warehouseRequest = warehouseRequest;
        this.enterprise=enterprise;
        this.account=account;
        populaterequest(warehouseRequest);
    }
    
    public void populaterequest(WarehouseWorkRequest record){
        addressDisp.setText(record.getShippingAddress());
        invoiceDisp.setText(record.getInvoice()+"");
        if(record.getDriver()!=""){
            driverTxt.setText(record.getDriver());
        }
        if(record.getVehicleNum()!=""){
            vehicleTxt.setText(record.getVehicleNum());
        }
        loadButton.setEnabled(false);
        if(record.isOrderStatus()==2){
            loadButton.setEnabled(true);
            pickupButton.setEnabled(false);
        }
        if(record.isOrderStatus()==3){
            loadButton.setEnabled(false);
            pickupButton.setEnabled(false);
        }
        
    }  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pickupButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addressDisp = new javax.swing.JLabel();
        driverTxt = new javax.swing.JTextField();
        vehicleTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        invoiceDisp = new javax.swing.JLabel();

        pickupButton.setBackground(new java.awt.Color(71, 0, 0));
        pickupButton.setForeground(new java.awt.Color(255, 255, 255));
        pickupButton.setText("Pickup Shipment");
        pickupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickupButtonActionPerformed(evt);
            }
        });

        loadButton.setBackground(new java.awt.Color(71, 0, 0));
        loadButton.setForeground(new java.awt.Color(255, 255, 255));
        loadButton.setText("Load Vehicle for Delivery");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(71, 0, 0));
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("BACK");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Shipping Address:");

        jLabel7.setText("Driver:");

        jLabel8.setText("Vehicle Number:");

        addressDisp.setText("jLabel9");

        jLabel1.setText("Invoice Number:");

        invoiceDisp.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pickupButton)
                .addGap(80, 80, 80)
                .addComponent(loadButton)
                .addGap(506, 506, 506))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(vehicleTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(driverTxt)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(invoiceDisp)
                                    .addComponent(addressDisp, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))))))
                .addGap(564, 564, 564))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backJButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(invoiceDisp)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressDisp)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(driverTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(vehicleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pickupButton)
                    .addComponent(loadButton))
                .addContainerGap(307, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pickupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickupButtonActionPerformed
        // TODO add your handling code here:
       // BillingWorkRequest price= new BillingWorkRequest();
        this.generateClicked=true;
        warehouseRequest.setOrderStatus(2);
        warehouseRequest.setDriver(driverTxt.getText());
        warehouseRequest.setVehicleNum(vehicleTxt.getText());
        loadButton.setEnabled(true);
       // this.setTotalPrice(price.productPrice.get(this.warehouseRequest.getProductName().toUpperCase())*this.warehouseRequest.getQuantity());
    }//GEN-LAST:event_pickupButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        
        this.generateClicked=true;
        warehouseRequest.setOrderStatus(3);
    }//GEN-LAST:event_loadButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        TransportWorkAreaJPanel dwjp = (TransportWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressDisp;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField driverTxt;
    private javax.swing.JLabel invoiceDisp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton pickupButton;
    private javax.swing.JTextField vehicleTxt;
    // End of variables declaration//GEN-END:variables
}
