/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BillingRole;
import Business.Enterprise.Enterprise;
import Business.Organization.BillingOrganization;
import Business.Organization.Organization;
import Business.Organization.TransportOrganization;
import Business.UserAccount.UserAccount;
import java.util.HashMap;
import Business.WorkQueue.BillingWorkRequest;
import Business.WorkQueue.WarehouseWorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author arpit
 */
public class BillProcessJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BillProcessJPanel
     */
    JPanel userProcessContainer;
    WarehouseWorkRequest warehouseRequest;
    static boolean generateClicked=false;
    Enterprise enterprise;
    UserAccount account;
    public int totalPrice;

    public int getTotalPrice() {
        return totalPrice;
    }

    public void setTotalPrice(int totalPrice) {
        this.totalPrice = totalPrice;
    }
    public BillProcessJPanel(JPanel userProcessContainer, WarehouseWorkRequest warehouseRequest, Enterprise enterprise, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.warehouseRequest = warehouseRequest;
        populaterequest(warehouseRequest);
        this.enterprise=enterprise;
        this.account=account;
    }
    
    public void populaterequest(WarehouseWorkRequest record){
        BillingWorkRequest price= new BillingWorkRequest();
        prodNameDispTxt.setText(record.getProductName());
        String quantity= record.getQuantity()+"";
        addressTxt.setEnabled(false);
        quantityDisplayTxt.setText(quantity);
        priceDisplayTxt.setText(price.productPrice.get(record.getProductName().toUpperCase())+"");
        if(!generateClicked)
         totalPriceDisplayTxt.setText("");
        if(warehouseRequest.getTotalPrice()>-1){
            totalPriceDisplayTxt.setText(warehouseRequest.getTotalPrice()+"");
        }
        warehouseRequest.getShippingAddress();
        if(warehouseRequest.getShippingAddress()!=""){
           packJButton.setEnabled(false);
           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        prodNameDispTxt = new javax.swing.JLabel();
        quantityDisplayTxt = new javax.swing.JLabel();
        priceDisplayTxt = new javax.swing.JLabel();
        totalPriceDisplayTxt = new javax.swing.JLabel();
        generateBillJButton = new javax.swing.JButton();
        packJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 144, 22));

        jLabel2.setBackground(new java.awt.Color(71, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Invoice Draft");

        backJButton.setBackground(new java.awt.Color(71, 0, 0));
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("BACK");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel1.setText("Product Name");

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("Quantity");

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("Price");

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setText("Total");

        prodNameDispTxt.setText("jLabel6");

        quantityDisplayTxt.setText("jLabel7");

        priceDisplayTxt.setText("jLabel8");

        totalPriceDisplayTxt.setText("jLabel9");

        generateBillJButton.setBackground(new java.awt.Color(71, 0, 0));
        generateBillJButton.setForeground(new java.awt.Color(255, 255, 255));
        generateBillJButton.setText("GENERATE BILL");
        generateBillJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBillJButtonActionPerformed(evt);
            }
        });

        packJButton.setBackground(new java.awt.Color(71, 0, 0));
        packJButton.setForeground(new java.awt.Color(255, 255, 255));
        packJButton.setText("CONFIRM PACKING");
        packJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packJButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Enter Shipping Address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generateBillJButton)
                .addGap(259, 259, 259))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(prodNameDispTxt))
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(quantityDisplayTxt))
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(priceDisplayTxt))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalPriceDisplayTxt)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(54, 54, 54)
                                .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton)
                        .addGap(318, 318, 318)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(609, 609, 609)
                        .addComponent(packJButton)))
                .addGap(203, 203, 203))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(jLabel2))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodNameDispTxt)
                    .addComponent(quantityDisplayTxt)
                    .addComponent(priceDisplayTxt)
                    .addComponent(totalPriceDisplayTxt))
                .addGap(52, 52, 52)
                .addComponent(generateBillJButton)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(packJButton)
                .addContainerGap(196, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        BillingWorkAreaJPanel dwjp = (BillingWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void generateBillJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBillJButtonActionPerformed
        // TODO add your handling code here:
        BillingWorkRequest price= new BillingWorkRequest();
        this.generateClicked=true;
        totalPriceDisplayTxt.setText((price.productPrice.get(this.warehouseRequest.getProductName().toUpperCase())*this.warehouseRequest.getQuantity())+"");
        warehouseRequest.setTotalPrice(price.productPrice.get(this.warehouseRequest.getProductName().toUpperCase())*this.warehouseRequest.getQuantity());
        this.setTotalPrice(price.productPrice.get(this.warehouseRequest.getProductName().toUpperCase())*this.warehouseRequest.getQuantity());
        warehouseRequest.setInvoice();
        addressTxt.setEnabled(true);
        packJButton.setEnabled(true);
    }//GEN-LAST:event_generateBillJButtonActionPerformed

    private void packJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packJButtonActionPerformed
        // TODO add your handling code here:
        if(warehouseRequest.getShippingAddress()==""){
           // JOptionPane.showMessageDialog("Please enter shipping address");
            JOptionPane.showMessageDialog(this, "Please enter shipping address");
            return;
        }
        warehouseRequest.setShippingAddress(addressTxt.getText());
                
        
          Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof TransportOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getworkRequestOrderList().add(this.warehouseRequest);
            account.getWorkQueue().getworkRequestOrderList().add(this.warehouseRequest);
        }
    }//GEN-LAST:event_packJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton generateBillJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton packJButton;
    private javax.swing.JLabel priceDisplayTxt;
    private javax.swing.JLabel prodNameDispTxt;
    private javax.swing.JLabel quantityDisplayTxt;
    private javax.swing.JLabel totalPriceDisplayTxt;
    // End of variables declaration//GEN-END:variables
}
